### ISSUE TITLE
Useful image names

### ISSUE THREAD

**Issue by NowakO** [i10/ARPen#4]
Some image files in /Documentation/images are still named IMG***, what makes searching an image in the browser hard.

**Comment by imkrishsub** [comment]
Any idea what the 'IMG_1501.JPG' shows? These files were added by Felix, but they are not currently linked to README.md.

**Comment by flashspys** [comment]
This image shows the connection of the ground levels from all buttons. Its basically a 3 to 1 connection. But this is a quite dirty solution, not really recommendable.
