### ISSUE TITLE
iPhone Simulator not supported

### ISSUE THREAD

**Issue by Zaubentrucker** [i10/ARPen#5]
Since the aruco and opencv2 libraries only support arm64, the Xcode simulator can't be used (as it only supports x86). 
The ARPen will usually not be debugged via a simulator but developers might still run into confusing error messages when they set up the project.

I suggest to either mention the inability to use the simulator in the README, or to build the libraries with additional x86 support.

**Comment by imkrishsub** [comment]
Thanks! I have added the instructions to the [developer guide](https://github.com/i10/ARPen/wiki/Developing-for-ARPen) and linked it to [README](https://github.com/i10/ARPen/blob/master/README.md).
