### ISSUE TITLE
Remove Carthage Search Parts from Xcodeproject

### ISSUE THREAD

**Issue by Zaubentrucker** [i10/ARPen#6]
On building the iOS App, the linker issues a "file not found" warning as it can't find the Carthage files.

Since it seems like Carthage isn't used anymore, I suggest to remove the Carthage Path from the Framework Search Paths in:
ARPen ->Build Settings -> Search Paths -> Framework Search Paths

**Comment by imkrishsub** [comment]
Fixed—thanks!
