### ISSUE TITLE
Arduino Sketch and ReadMe not consistent

### ISSUE THREAD

**Issue by Zaubentrucker** [i10/ARPen#8]
In the file `ARPen/ARPen/Bluetooth Software/BLE_Serial/BLE_Serial.ino` the buttons are defined as follows:

```c++
const int button1Pin = D5;     // the number of the pushbutton pin
const int button2Pin = D0;
const int button3Pin = D4;
```

But the Fritzing diagrams in the ReadMe show that D0 is not connected and instead D3 is used:
![bluetooth setup](https://user-images.githubusercontent.com/13556914/51475293-3b56a980-1d82-11e9-92e6-5b4e1793a5d4.jpg)

See this image for reference on the pinout of the BLE Nano 2:
![nano2_pinout](https://user-images.githubusercontent.com/13556914/51474902-11e94e00-1d81-11e9-8e24-1df93a42d637.png)

**Comment by imkrishsub** [comment]
Yes, you are right. The Fritzing diagram is incorrect—will fix it. Thanks!
